<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>js</string>
	</array>
	<key>name</key>
	<string>NodeJs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.js</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.js.nodejs</string>
	<key>uuid</key>
	<string>5030ef23-8cdf-497a-82ee-2340326c6234</string>
</dict>
</plist>